name: "arraypromise"
version: "0.6.1"
author: "Michiel Dral <michiel@sunsethosting.co.uk>"
description: >
  An promise, on which you can apply array methods.
  For when you are sure the promise will return an array!
  
main: "./index.coffee"

repository: 
  type: "git"
  url: "https://github.com/dralletje/ArrayPromise.git"
  
keywords: 
  - "promises"
  - "array"

dependencies: 
  kew: "*"
  async: "*"
  
# Need to fix these, get them global or something
devDependencies: 
  coffee-script: "*"
  npm-yaml: "*"
  better-stack-traces: "*"
  
  # Tests
  chai: "*"
  chai-as-promised: "*"
  grunt: "*"
  grunt-contrib-coffee: "*"
  grunt-contrib-watch: "*"
  grunt-simple-mocha: "*"
  ## Not sure wether or not to add this one :/
  #mocha: *
  
license: "GLP v2.0"
engines: 
  node: ">=0.10"
